# Get common recipes
recipes = ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/recipes.rake'
import recipes

$jobid = ENV['jobid']

# Figure out what run period we are in
$period = '7TeV'
if $jobid.include? '8TeV'
  $period = '8TeV'
end

################################################################################
## Refreshing cython proxies ###################################################
################################################################################


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end

#puts get_sample_names('data_DoubleMu')

samples = Hash[
  #"ewk" => Array['Zjets_M50', 'WplusJets_madgraph', 
    #'ZZJetsTo4L_pythia',
  #  'TTplusJets_madgraph'] + get_sample_names('WZ') + get_sample_names('WWJet') + get_sample_names('ZZ'),
  "ewk" => Array['TTplusJets_madgraph'] + get_sample_names('WZ') + get_sample_names('ZZ'), 
  #"key_shapes" => Array['WZJetsTo3LNu_pythia', 'ZZJetsTo4L_pythia', 'MSSM_A_ZH_FastSim'],
  "key_shapes" => get_sample_names('Zh-lltt-FullSim'),
  #"wjets" => Array['WplusJets_madgraph'],
  #"zjets" => Array['Zjets_M50'],
  #"zjets" => Array['Z1jet_M50'], 
  #"ttbar" => Array['TTplusJets_madgraph'],
  #"A300-Zh-lltt-FullSim_checkMVAMET" => get_sample_names('A300-Zh-lltt-FullSim_checkMVA'),  
  "A300-Zh-lltt-FullSim_checkMVAMET" => Array['A300-Zh-lltt-FullSim_checkMVAMET'],  
  #Important Backgrounds (Aug 6, 2014):
  "TTZJets" => Array['TTZJets'],
  "ggzz2l2l" => Array['ggZZ2L2L'],
  "VH_H2Tau_M-125" => Array['VH_H2Tau_M-125'],
  "VHWW_lepdecay_125" => Array['VHWW_lepdecay_125'],
  "ZZJetsTo4L_pythia" => Array['ZZJetsTo4L_pythia'],
  "WJetsToLNu" => Array['WJetsToLNu'],
  # End important backgrounds

  "ZZ" => get_sample_names('ZZ'), #will include ZZJets4L and ggZZ2L2L
  #MCToAnalyze" => get_sample_names('VH_H2Tau_M-125') + get_sample_names('VHWW_lepdecay_125') + get_sample_names('ggZZ2L2L') + get_sample_names('TTZJets') + get_sample_names('ZZJetsTo4L_pythia'),
  "MCToAnalyze" => Array['VH_H2Tau_M-125','VHWW_lepdecay_125','ggZZ2L2L','TTZJets','ZZJetsTo4L_pythia', 'ZZZ', 'WZZ', 'WWZ'], 
  #"signal" => get_sample_names('VH') + get_sample_names('WH'),
  "signal" => Array['VH_H2Tau_M-125','VHWW_lepdecay_125', 'ggZZ2L2L'],
  #"VH_H2Tau_M-125" => Array['VH_H2Tau_M-125'],
  #"signal_mmtt" => get_sample_names('Zh-mmtt'), + Array['VH_H2Tau_M-125'],
  #"signal_eett" => get_sample_names('Zh-eett'), + Array['VH_H2Tau_M-125'],
  "signal_mmtt" => Array['VH_H2Tau_M-125'],
  "signal_eett" => Array['VH_H2Tau_M-125'],
  "fullsim" => get_sample_names('Zh-lltt-FullSim'),
  "fullsim300" => Array['A300-Zh-lltt-FullSim'],
  "fullsim_madgraph" => get_sample_names('AToZhToLLTauTau-MadGraph'),
  #"madgraph" => get_sample_names('Zh-lltt-MadGraph'),
  "madgraph" => get_sample_names('Zh-lltt-MadGraph'),
  #"signal_125" => Array['VH_H2Tau_M-125'],
  # Automagically figure out what data samples we have
  "data_mm" =>  get_sample_names('data_DoubleMu'),
  "data_ee" => get_sample_names('data_DoubleElectron'),
  "A300-MG-svFit" => get_sample_names('A300-Zh-lltt-svFit-MadGraph-TES'),
]

 #puts "diboson: " + samples["diboson"].inspect
 #puts "fullsim: " + samples["fullsim"].inspect
# puts "MCToAnalyze: " + samples["MCToAnalyze"].inspect
# puts "madgraph: " + samples["madgraph"].inspect
# puts "A300-MG-svFit: " + samples["A300-MG-svFit"].inspect
# puts "data_mm: " + samples["data_mm"].inspect
# puts "data_ee: " + samples["data_ee"].inspect
# puts "A300-Zh-lltt-FullSim_checkMVAMET: " + samples["A300-Zh-lltt-FullSim_checkMVAMET"].inspect

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end

################################################################################
## Recipes to measure fake rates 
##  targets:
##     fakerates - measure all fakerates
################################################################################

# Map which samples need to be analyzed by which analyzer
fr_analyzer_sample_map = Hash[
  "EFakeRateEEET.py"    => samples['data_ee'] + samples['MCToAnalyze'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
  "EFakeRateMMET.py"    => samples['data_mm'] + samples['MCToAnalyze'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
  "MUFakeRateEEMT.py"   => samples['data_ee'] + samples['MCToAnalyze'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
  "MUFakeRateMMMT.py"   => samples['data_mm'] + samples['MCToAnalyze'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
  "TauFakeRatesEETT.py" => samples['MCToAnalyze'] + samples['data_ee'],# + samples["wjets"],# + Array["TTplusJets_madgraph"],
  "TauFakeRatesMMTT.py" => samples['MCToAnalyze'] + samples['data_mm'],# + samples["wjets"],# + Array["TTplusJets_madgraph"],
  "TauFakeRatesEEMT.py" => samples['MCToAnalyze'] + samples['data_ee'],
  "TauFakeRatesEEET.py" => samples['MCToAnalyze'] + samples['data_ee'],
  "TauFakeRatesMMET.py" => samples['MCToAnalyze'] + samples['data_mm'],
  "TauFakeRatesMMMT.py" => samples['MCToAnalyze'] + samples['data_mm'],
 ]

#fr_analyzer_sample_map = Hash[
#  "EFakeRateEEET.py"    => samples['data_ee'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
#  "EFakeRateMMET.py"    => samples['data_mm'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
#  "MUFakeRateEEMT.py"   => samples['data_ee'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
#  "MUFakeRateMMMT.py"   => samples['data_mm'],# + samples["wjets"],# + Array["TTplusJets_madgraph"], # 
#  "TauFakeRatesEETT.py" => samples['data_ee'],# + samples["wjets"],# + Array["TTplusJets_madgraph"],
#  "TauFakeRatesMMTT.py" => samples['data_mm'],# + samples["wjets"],# + Array["TTplusJets_madgraph"],
#  "TauFakeRatesEEMT.py" => samples['data_ee'],
#  "TauFakeRatesEEET.py" => samples['data_ee'],
#  "TauFakeRatesMMET.py" => samples['data_mm'],
#  "TauFakeRatesMMMT.py" => samples['data_mm'],
# ]

fr_analyzer_dependencies = Hash[
  "EFakeRateEEET.py"    => Array["EMUFakeRatesBase.py","baseSelections.py",],  # "EEETauTree.py",   ],
  "EFakeRateMMET.py"    => Array["EMUFakeRatesBase.py","baseSelections.py",],  # "MuMuETauTree.py", ],
  "MUFakeRateEEMT.py"   => Array["EMUFakeRatesBase.py","baseSelections.py",],  # "EEMuTauTree.py",  ],
  "MUFakeRateMMMT.py"   => Array["EMUFakeRatesBase.py","baseSelections.py",],  # "MuMuMuTauTree.py",],
  "TauFakeRatesEETT.py" => Array["TauFakeRatesBase.py","baseSelections.py",],  # "EETauTauTree.py",],
  "TauFakeRatesMMTT.py" => Array["TauFakeRatesBase.py","baseSelections.py",],  # "MuMuTauTauTree.py",],
  "TauFakeRatesEEMT.py" => Array["TauFakeRatesBaseZLT.py","baseSelections.py",],
  "TauFakeRatesEEET.py" => Array["TauFakeRatesBaseZLT.py","baseSelections.py",],
  "TauFakeRatesMMET.py" => Array["TauFakeRatesBaseZLT.py","baseSelections.py",],
  "TauFakeRatesMMMT.py" => Array["TauFakeRatesBaseZLT.py","baseSelections.py",],
]

# Create an empty placeholder to enable tab-completion
task :fakerates => []
# Create tasks for each sample + analyzer
#chec/ if base class or some selections has changed
fr_analyzer_dependencies.each do |analyzer, deps|
  file analyzer => fr_analyzer_dependencies[analyzer] do |t|
   #puts t.investigation
    sh "touch #{t.name}"
  end
end

fr_analyzer_sample_map.each do |analyzer, the_samples|
  #puts "Creating tasks for analyzer: #{analyzer}"
  get_analyzer_results(analyzer, the_samples).each do |result|
    #file result => fr_analyzer_dependencies[analyzer]
    task :fakerates => result
  end
end

#puts :fakerates
# puts "\n\:fakerates.methods : ["+ :fakerates.methods.sort.join("  ").to_s+"]"
# puts :fakerates.public_methods

################################################################################
## Recipes to fit fake rates
##  targets:
##     fits
################################################################################

# Output directory
$frfit_dir = "results/#{$jobid}/fakerate_fits"
directory $frfit_dir

# Common fit functions
exponential = "scale*TMath::Exp(x*decay)+offset"
exponential_vars =  "scale[0.5, 0, 5],decay[-1e-2, -1, -1e-4],offset[1e-2, 0, 0.5]"

exponential2 = "scale*TMath::Exp(x*decay)"
exponential2_vars =  "scale[0.5, 0, 5],decay[-1e-2, -1, -1e-4]"

exp_rise = "scale*TMath::Exp(x*decay)"
exp_rise_vars =  "scale[-0.5, -5, 0],decay[-1e-2, -1, -1e-4]"

rise = "0.5*scale*(1+ TMath::Erf( (x - mu)/ sigma ) )+offset"
rise_vars = "scale[0.03, 1e-4, 1],mu[45, 20, 60],sigma[20, 10, 30],offset[0.006, 1e-5, 0.5]"

landau = "scale*TMath::Landau(x,mu,sigma,0)+offset"
landau_vars =  "scale[0.5, 0, 5],mu[5, 0, 100],sigma[1.9, 0.1, 20],offset[1e-2, 0, 0.5]"

flat = "offset"
flat_vars =  "offset[1e-2, 0, 0.5]"

# Fake rate fit configurations
fr_fits = Hash[
  # Format is type_region_denom_num_variable
  #
  # E/MU LOOSE ID PT
  #
  #"m_zlt_pt10_looseId_muonPt" => Hash[
  #  "samples" => Array["data_mm", "data_ee", "diboson"], #],#"ewk", 
  #  "analyzer" => "MUFakeRate??MT",
  #  "function" => flat,
  #  "variables" => flat_vars,
   # "corr"      => "--noCorrection true",
  #  "rebin" => 10,
  #  "range" => "10 100",
  #],
  #"e_zlt_pt10_looseId_electronPt" => Hash[
  #  "samples" => Array[ "data_mm", "data_ee", "diboson"], #],#"ewk",
  #  "analyzer" => "EFakeRate??ET",
  #  "function" => rise,
  #  "variables" => rise_vars,
  # # "corr"      => "--noCorrection true",
  #  "rebin" => 10,
  #  "range" => "10 100",
  #],
  #
  # E/MU TIGHT ID PT
  #
  #"m_zlt_pt10_tightId_muonPt" => Hash[
  #  "samples" => Array[ "data_mm", "data_ee", "diboson"], #],#"ewk",
  #  "analyzer" => "MUFakeRate??MT",
  #  "function" => flat,
  #  "variables" => flat_vars,
  # # "corr"      => "--noCorrection true",
  #  "rebin" => 10,
  #  "range" => "10 100",
  #],
  #"e_zlt_pt10_tightId_electronPt" => Hash[
  #  "samples" => Array[ "data_mm", "data_ee", "diboson"], #],#"ewk",
  #  "analyzer" => "EFakeRate??ET",
  #  "function" => rise,
  #  "variables" => rise_vars,
  # # "corr"      => "--noCorrection true",
  #  "rebin" => 10,
  #  "range" => "10 100",
  #],
  #
  # E/MU LOOSE ID JETPT
  #####
  "m_zlt_pt10_looseId_muonJetPt" => Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
    "analyzer" => "MUFakeRate??MT",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
#$  "m_zlt_pt10_looseId_muonJetPtBarrel" => Hash[
#$    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#$    "analyzer" => "MUFakeRate??MT",
#$    "function" => exponential,
#$    "variables" => exponential_vars,
#$    "corr"      => "--noCorrection true",
#$    "rebin" => 10,
#$    "range" => "10 150",
#$  ],
#$  "m_zlt_pt10_looseId_muonJetPtEndCap" => Hash[
#$    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#$    "analyzer" => "MUFakeRate??MT",
#$    "function" => exponential,
#$    "variables" => exponential_vars,
#$    "corr"      => "--noCorrection true",
#$    "rebin" => 10,
#$    "range" => "10 150",
#$  ],
  "e_zlt_pt10_looseId_electronJetPt" => Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
    "analyzer" => "EFakeRate??ET",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
#  "e_zlt_pt10_looseId_electronJetPtLow" => Hash[
#    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#    "analyzer" => "EFakeRate??ET",
#    "function" => exponential,
#    "variables" => exponential_vars,
#    "corr"      => "--noCorrection true",
#    "rebin" => 10,
#    "range" => "10 150",
#  ],
#  "e_zlt_pt10_looseId_electronJetPtMedium" => Hash[
#    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#    "analyzer" => "EFakeRate??ET",
#    "function" => exponential,
#    "variables" => exponential_vars,
#    "corr"      => "--noCorrection true",
#    "rebin" => 10,
#    "range" => "10 150",
#  ],
#  "e_zlt_pt10_looseId_electronJetPtHigh" => Hash[
#    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#    "analyzer" => "EFakeRate??ET",
#    "function" => exponential,
#    "variables" => exponential_vars,
#    "corr"      => "--noCorrection true",
#    "rebin" => 10,
#    "range" => "10 150",
#  ],
  "e_zlt_pt10_looseId_electronJetPtBarrel" => Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
    "analyzer" => "EFakeRate??ET",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
  "e_zlt_pt10_looseId_electronJetPtEndCap" => Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
    "analyzer" => "EFakeRate??ET",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
  ##
  ## E/MU TIGHT ID JETPT
  ##
  "m_zlt_pt10_tightId_muonJetPt" => Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
    "analyzer" => "MUFakeRate??MT",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
#$  "m_zlt_pt10_tightId_muonJetPtBarrel" => Hash[
#$    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#$    "analyzer" => "MUFakeRate??MT",
#$    "function" => exponential,
#$    "variables" => exponential_vars,
#$    "corr"      => "--noCorrection true",
#$    "rebin" => 10,
#$    "range" => "10 150",
#$  ],
#$  "m_zlt_pt10_tightId_muonJetPtEndCap" => Hash[
#$    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#$    "analyzer" => "MUFakeRate??MT",
#$    "function" => exponential,
#$    "variables" => exponential_vars,
#$    "corr"      => "--noCorrection true",
#$    "rebin" => 10,
#$    "range" => "10 150",
#$  ],
  "e_zlt_pt10_tightId_electronJetPt" => Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
    "analyzer" => "EFakeRate??ET",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
#  "e_zlt_pt10_tightId_electronJetPtLow" => Hash[
#    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#    "analyzer" => "EFakeRate??ET",
#    "function" => exponential,
#    "variables" => exponential_vars,
#    "corr"      => "--noCorrection true",
#    "rebin" => 10,
#    "range" => "10 150",
#  ],
#  "e_zlt_pt10_tightId_electronJetPtMedium" => Hash[
#    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#    "analyzer" => "EFakeRate??ET",
#    "function" => exponential,
#    "variables" => exponential_vars,
#    "corr"      => "--noCorrection true",
#    "rebin" => 10,
#    "range" => "10 150",
#  ],
#  "e_zlt_pt10_tightId_electronJetPtHigh" => Hash[
#    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#    "analyzer" => "EFakeRate??ET",
#    "function" => exponential,
#    "variables" => exponential_vars,
#    "corr"      => "--noCorrection true",
#    "rebin" => 10,
#    "range" => "10 150",
#  ],
#$  "e_zlt_pt10_tightId_electronJetPtBarrel" => Hash[
#$    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#$    "analyzer" => "EFakeRate??ET",
#$    "function" => exponential,
#$    "variables" => exponential_vars,
#$    "corr"      => "--noCorrection true",
#$    "rebin" => 10,
#$    "range" => "10 150",
#$  ],
#$  "e_zlt_pt10_tightId_electronJetPtEndCap" => Hash[
#$    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"], #],#"ewk", 
#$    "analyzer" => "EFakeRate??ET",
#$    "function" => exponential,
#$    "variables" => exponential_vars,
#$    "corr"      => "--noCorrection true",
#$    "rebin" => 10,
#$    "range" => "10 150",
#$  ],
  #
  # TAUS
  #
  #"t_ztt_pt10_MediumIso_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5, 
  #  "range" => "10 100",
  #],

  #"t_ztt_pt10_TightIso_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],

  #"t_ztt_pt10_LooseMVAIso_tauPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],
  #"t_ztt_pt10_LooseIso_tauPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],
  #"t_ztt_pt10_MediumMVAIso_tauPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],
  #"t_ztt_pt10_LooseIso3Hits_tauPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "15 150",
  #],
  "t_ztt_pt10low_LooseIso3Hits_tauJetPt_ltau" =>  Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"],
    "analyzer" => "TauFakeRates???T",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr" => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
  "t_ztt_pt10high_LooseIso3Hits_tauJetPt_ltau" =>  Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"],
    "analyzer" => "TauFakeRates???T",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr" => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],

  ##We use MediumIso in TT channels
  #"t_ztt_pt10high_LooseIso3Hits_tauJetPt_tautau" =>  Hash[
  #  "samples" => Array["data_mm", "data_ee", "MCToAnalyze"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "corr" => "--noCorrection true",
  #  "rebin" => 10,
  #  "range" => "20 150",
  #],
  #"t_ztt_pt10low_LooseIso3Hits_tauJetPt_tautau" =>  Hash[
  #  "samples" => Array["data_mm", "data_ee", "MCToAnalyze"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "corr" => "--noCorrection true",
  #  "rebin" => 10,
  #  "range" => "20 150",
  #],
  "t_ztt_pt10low_MediumIso3Hits_tauJetPt_tautau" =>  Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"],
    "analyzer" => "TauFakeRates??TT",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
  "t_ztt_pt10high_MediumIso3Hits_tauJetPt_tautau" =>  Hash[
    "samples" => Array["data_mm", "data_ee", "MCToAnalyze"],
    "analyzer" => "TauFakeRates??TT",
    "function" => exponential,
    "variables" => exponential_vars,
    "corr"      => "--noCorrection true",
    "rebin" => 10,
    "range" => "10 150",
  ],
  #"t_ztt_pt10_lo_MediumIso3Hits_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "15 150",
  #],
  #"t_ztt_pt10_hi_MediumIso3Hits_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "15 150",
  #],
  #"t_ztt_pt10_TightMVAIso_tauPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],
  #"t_ztt_pt10_TightIso_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],
  # taus
  #"t_ztt_pt10-antiElMVATight-antiMuLoose_MediumIso_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],
  #"t_ztt_pt10-antiElMed-antiMuMed_TightIso_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #],  
  #"t_ztt_pt10-antiElLoose-antiMuTight_MediumIso_tauJetPt" =>  Hash[
  #  "samples" => Array["diboson", "data_mm", "data_ee"],
  #  "analyzer" => "TauFakeRates??TT",
  #  "function" => exponential,
  #  "variables" => exponential_vars,
  #  "rebin" => 5,
  #  "range" => "10 100",
  #]
 
  
]

# Placeholder
task :fits => []

# Create tasks for all the fr_fits
fr_fits.each do |fit, fit_info|
  fit_configuration = fit.split("_")
  #puts "fit_config: " + fit_configuration[1] + " " + fit_configuration[2] + " " + fit_configuration[3] + " " + fit_configuration[4]
  #puts "fit_config2: " + fit_configuration.inspect
  region = fit_configuration[1]
  denom = fit_configuration[2]
  num = fit_configuration[3]
  var = fit_configuration[4]

  # Expand sample list
  subsample_inputs = []
  fit_info['samples'].each do |sample|
    #puts sample.inspect + ": " + samples[sample].inspect
    subsample_inputs += samples[sample]
  end

  fit_output = $frfit_dir + "/#{fit}.root"
  subsamples_inputs_result_list = subsample_inputs.map{|x|  "results/#{$jobid}/#{fit_info['analyzer']}/#{x}.root"}
  #puts "subsamples_inputs_result_list: " + subsamples_inputs_result_list.inspect
  mergedTargets = Array[]
  subsamples_inputs_result_list.each do |regexFile|
    #target = regexFile.sub('??','Z') 
    if (regexFile.count('?') == 2)
      target = regexFile.sub('??','Z')
    else
      target = regexFile.sub('???', 'ZL')
      regexFile = regexFile.sub('???', '{??M,??E}')
    end
    mergedTargets << target
    deps   = Dir.glob(regexFile)
    mergedir= File.dirname(target)
    file target => deps do |t|
      #puts "merging #{regexFile} into #{target}"
      sh "mkdir -p #{mergedir}"
      sh "hadd -f #{target} #{regexFile}" 
    end
  end
  
  subsample_input_list = mergedTargets.join(" ")
  # 
  # # Path to histograms in root files
  denom_path = Array[region, denom, var].join("/")
  num_path = Array[region, denom, num, var].join("/")
  
  # Correct the numerator and denominator for WZ + ZZ contamination -- ASK EVAN IF IT IS CORRECT
  # The output is stored in "numerator" and "denominator"
  corrected_file = fit_output.sub('.root', '.corrected_inputs.root')
  file corrected_file => mergedTargets + Dir.glob(fit_info['analyzer'] + '.py') + ["CorrectFakeRateData.py"] do |t|
    sh "mkdir -p #{$frfit_dir}"
    # debugging
    #puts "python CorrectFakeRateData.py --files #{subsample_input_list} --lumifiles inputs/#{$jobid}/*sum --outputfile #{t.name} --numerator '#{num_path}' --denom '#{denom_path}' --rebin #{fit_info['rebin']} #{fit_info['corr']}"
    sh "python CorrectFakeRateData.py --files #{subsample_input_list} --lumifiles inputs/#{$jobid}/*sum --outputfile #{t.name} --numerator '#{num_path}' --denom '#{denom_path}' --rebin #{fit_info['rebin']} #{fit_info['corr']}"
  end
  
  #puts fit_output
  #puts corrected_file
  file fit_output => [corrected_file, ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/StatTools/scripts/fit_efficiency_chi2.py'] do |t| # ] do |t| #
    sh "fit_efficiency_chi2.py #{fit_output} numerator denominator \'#{fit_info['function']}\' \'#{fit_info['variables']}\' #{corrected_file} --plot --xrange #{fit_info['range']} --xtitle #{var} --grid"
  end
  task :fits => fit_output #corrected_file

end

################################################################################
## Recipes to analyze ZH
##  targets:
##     mmt
################################################################################

analyzer_dependencies = Hash[
  "ZHAnalyzeMMMT.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
  "ZHAnalyzeEEMT.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
  "ZHAnalyzeMMET.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
  "ZHAnalyzeEEET.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
  "ZHAnalyzeMMEM.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
  "ZHAnalyzeEEEM.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
  "ZHAnalyzeMMTT.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
  "ZHAnalyzeEETT.py" => Array["baseSelections.py", "mcCorrectors.py", "ZHAnalyzerBase.py", "fake_rate_functions.py"],
]

#check if base class or some selections has changed
analyzer_dependencies.each do |analyzer, deps|
  #puts analyzer
  #puts deps.inspect
  file analyzer => deps do |t|
    #puts t.investigation
    sh "touch #{t.name}"
  end
end

task :mmmt_A300_MG_svFit => get_analyzer_results("ZHAnalyzeMMMT", samples['A300-MG-svFit'])
task :eemt_A300_MG_svFit => get_analyzer_results("ZHAnalyzeEEMT", samples['A300-MG-svFit'])
task :mmet_A300_MG_svFit => get_analyzer_results("ZHAnalyzeMMET", samples['A300-MG-svFit'])
task :eeet_A300_MG_svFit => get_analyzer_results("ZHAnalyzeEEET", samples['A300-MG-svFit'])
task :mmem_A300_MG_svFit => get_analyzer_results("ZHAnalyzeMMEM", samples['A300-MG-svFit'])
task :eeem_A300_MG_svFit => get_analyzer_results("ZHAnalyzeEEEM", samples['A300-MG-svFit'])
task :mmtt_A300_MG_svFit => get_analyzer_results("ZHAnalyzeMMTT", samples['A300-MG-svFit'])
task :eett_A300_MG_svFit => get_analyzer_results("ZHAnalyzeEETT", samples['A300-MG-svFit'])

task :mmmt_A300FS => get_analyzer_results("ZHAnalyzeMMMT", samples['A300-Zh-lltt-FullSim_checkMVAMET'])
task :eemt_A300FS => get_analyzer_results("ZHAnalyzeEEMT", samples['A300-Zh-lltt-FullSim_checkMVAMET'])
task :mmet_A300FS => get_analyzer_results("ZHAnalyzeMMET", samples['A300-Zh-lltt-FullSim_checkMVAMET'])
task :eeet_A300FS => get_analyzer_results("ZHAnalyzeEEET", samples['A300-Zh-lltt-FullSim_checkMVAMET'])
task :mmem_A300FS => get_analyzer_results("ZHAnalyzeMMEM", samples['A300-Zh-lltt-FullSim_checkMVAMET'])
task :eeem_A300FS => get_analyzer_results("ZHAnalyzeEEEM", samples['A300-Zh-lltt-FullSim_checkMVAMET'])
task :mmtt_A300FS => get_analyzer_results("ZHAnalyzeMMTT", samples['A300-Zh-lltt-FullSim_checkMVAMET'])
task :eett_A300FS => get_analyzer_results("ZHAnalyzeEETT", samples['A300-Zh-lltt-FullSim_checkMVAMET'])

task :mmmt_signal_only => get_analyzer_results("ZHAnalyzeMMMT", samples['signal'])
task :eemt_signal_only => get_analyzer_results("ZHAnalyzeEEMT", samples['signal'])
task :mmet_signal_only => get_analyzer_results("ZHAnalyzeMMET", samples['signal'])
task :eeet_signal_only => get_analyzer_results("ZHAnalyzeEEET", samples['signal'])
task :mmem_signal_only => get_analyzer_results("ZHAnalyzeMMEM", samples['signal'])
task :eeem_signal_only => get_analyzer_results("ZHAnalyzeEEEM", samples['signal'])
task :mmtt_signal_only => get_analyzer_results("ZHAnalyzeMMTT", samples['signal'])
task :eett_signal_only => get_analyzer_results("ZHAnalyzeEETT", samples['signal'])

task :mmmt_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeMMMT", samples['ZZJetsTo4L_pythia'])
task :eemt_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeEEMT", samples['ZZJetsTo4L_pythia'])
task :mmet_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeMMET", samples['ZZJetsTo4L_pythia'])
task :eeet_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeEEET", samples['ZZJetsTo4L_pythia'])
task :mmem_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeMMEM", samples['ZZJetsTo4L_pythia'])
task :eeem_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeEEEM", samples['ZZJetsTo4L_pythia'])
task :mmtt_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeMMTT", samples['ZZJetsTo4L_pythia'])
task :eett_ZZJetsTo4L => get_analyzer_results("ZHAnalyzeEETT", samples['ZZJetsTo4L_pythia'])

task :mmmt_ggzz => get_analyzer_results("ZHAnalyzeMMMT", samples['ggzz2l2l'])
task :eemt_ggzz => get_analyzer_results("ZHAnalyzeEEMT", samples['ggzz2l2l'])
task :mmet_ggzz => get_analyzer_results("ZHAnalyzeMMET", samples['ggzz2l2l'])
task :eeet_ggzz => get_analyzer_results("ZHAnalyzeEEET", samples['ggzz2l2l'])
task :mmem_ggzz => get_analyzer_results("ZHAnalyzeMMEM", samples['ggzz2l2l'])
task :eeem_ggzz => get_analyzer_results("ZHAnalyzeEEEM", samples['ggzz2l2l'])
task :mmtt_ggzz => get_analyzer_results("ZHAnalyzeMMTT", samples['ggzz2l2l'])
task :eett_ggzz => get_analyzer_results("ZHAnalyzeEETT", samples['ggzz2l2l'])

task :mmmt_mg => get_analyzer_results("ZHAnalyzeMMMT", samples['madgraph'])
task :eemt_mg => get_analyzer_results("ZHAnalyzeEEMT", samples['madgraph'])
task :mmet_mg => get_analyzer_results("ZHAnalyzeMMET", samples['madgraph'])
task :eeet_mg => get_analyzer_results("ZHAnalyzeEEET", samples['madgraph'])
task :mmem_mg => get_analyzer_results("ZHAnalyzeMMEM", samples['madgraph'])
task :eeem_mg => get_analyzer_results("ZHAnalyzeEEEM", samples['madgraph'])
task :mmtt_mg => get_analyzer_results("ZHAnalyzeMMTT", samples['madgraph'])
task :eett_mg => get_analyzer_results("ZHAnalyzeEETT", samples['madgraph'])

task :mmmt_fs => get_analyzer_results("ZHAnalyzeMMMT", samples['fullsim'])
task :eemt_fs => get_analyzer_results("ZHAnalyzeEEMT", samples['fullsim'])
task :mmet_fs => get_analyzer_results("ZHAnalyzeMMET", samples['fullsim'])
task :eeet_fs => get_analyzer_results("ZHAnalyzeEEET", samples['fullsim'])
task :mmem_fs => get_analyzer_results("ZHAnalyzeMMEM", samples['fullsim'])
task :eeem_fs => get_analyzer_results("ZHAnalyzeEEEM", samples['fullsim'])
task :mmtt_fs => get_analyzer_results("ZHAnalyzeMMTT", samples['fullsim'])
task :eett_fs => get_analyzer_results("ZHAnalyzeEETT", samples['fullsim'])

task :mmmt_fs_mg => get_analyzer_results("ZHAnalyzeMMMT", samples['fullsim_madgraph'])
task :eemt_fs_mg => get_analyzer_results("ZHAnalyzeEEMT", samples['fullsim_madgraph'])
task :mmet_fs_mg => get_analyzer_results("ZHAnalyzeMMET", samples['fullsim_madgraph'])
task :eeet_fs_mg => get_analyzer_results("ZHAnalyzeEEET", samples['fullsim_madgraph'])
task :mmem_fs_mg => get_analyzer_results("ZHAnalyzeMMEM", samples['fullsim_madgraph'])
task :eeem_fs_mg => get_analyzer_results("ZHAnalyzeEEEM", samples['fullsim_madgraph'])
task :mmtt_fs_mg => get_analyzer_results("ZHAnalyzeMMTT", samples['fullsim_madgraph'])
task :eett_fs_mg => get_analyzer_results("ZHAnalyzeEETT", samples['fullsim_madgraph'])

task :mmmt => get_analyzer_results("ZHAnalyzeMMMT.py", samples['MCToAnalyze'] + samples['data_mm'] + samples['madgraph'])
task :eemt => get_analyzer_results("ZHAnalyzeEEMT.py", samples['MCToAnalyze'] + samples['data_ee'] + samples['madgraph'])
task :mmet => get_analyzer_results("ZHAnalyzeMMET.py", samples['MCToAnalyze'] + samples['data_mm'] + samples['madgraph'])
task :eeet => get_analyzer_results("ZHAnalyzeEEET.py", samples['MCToAnalyze'] + samples['data_ee'] + samples['madgraph'])
          
task :mmem => get_analyzer_results("ZHAnalyzeMMEM.py", samples['MCToAnalyze'] + samples['data_mm'] + samples['madgraph'])
task :eeem => get_analyzer_results("ZHAnalyzeEEEM.py", samples['MCToAnalyze'] + samples['data_ee'] + samples['madgraph'])
task :mmtt => get_analyzer_results("ZHAnalyzeMMTT.py", samples['MCToAnalyze'] + samples['data_mm'] + samples['madgraph'])
task :eett => get_analyzer_results("ZHAnalyzeEETT.py", samples['MCToAnalyze'] + samples['data_ee'] + samples['madgraph'])

task :data_only_mmmt => get_analyzer_results("ZHAnalyzeMMMT.py", samples['data_mm'])
task :data_only_eemt => get_analyzer_results("ZHAnalyzeEEMT.py", samples['data_ee'])
task :data_only_mmet => get_analyzer_results("ZHAnalyzeMMET.py", samples['data_mm'])
task :data_only_eeet => get_analyzer_results("ZHAnalyzeEEET.py", samples['data_ee'])
      
task :data_only_mmem => get_analyzer_results("ZHAnalyzeMMEM.py", samples['data_mm'])
task :data_only_eeem => get_analyzer_results("ZHAnalyzeEEEM.py", samples['data_ee'])
task :data_only_mmtt => get_analyzer_results("ZHAnalyzeMMTT.py", samples['data_mm'])
task :data_only_eett => get_analyzer_results("ZHAnalyzeEETT.py", samples['data_ee'])

task :abdollah_sync_mmmt => ["results/#{$jobid}/ZHAnalyzeMMMT/ZH_AbdollahSync.root"]
task :abdollah_sync_eemt => ["results/#{$jobid}/ZHAnalyzeEEMT/ZH_AbdollahSync.root"]
task :abdollah_sync_mmet => ["results/#{$jobid}/ZHAnalyzeMMET/ZH_AbdollahSync.root"]
task :abdollah_sync_eeet => ["results/#{$jobid}/ZHAnalyzeEEET/ZH_AbdollahSync.root"]

task :abdollah_sync_mmem => ["results/#{$jobid}/ZHAnalyzeMMEM/ZH_AbdollahSync.root"]
task :abdollah_sync_eeem => ["results/#{$jobid}/ZHAnalyzeEEEM/ZH_AbdollahSync.root"]
task :abdollah_sync_mmtt => ["results/#{$jobid}/ZHAnalyzeMMTT/ZH_AbdollahSync.root"]
task :abdollah_sync_eett => ["results/#{$jobid}/ZHAnalyzeEETT/ZH_AbdollahSync.root"]


#A Task to dominate all...
task :analyzezh => [:mmmt, :eemt, :mmet, :eeet, :mmem, :eeem, :mmtt, :eett] do
#task :analyzezh => [:mmmt, :eemt, :eeet, :eeem, :mmtt, :eett] do
#task :analyzezh => [:eeem, :mmtt, :eett] do
  puts "called analyzezh task from local rakefile"
end

task :analyzezh_A300FS => [:mmmt_A300FS, :eemt_A300FS, :mmet_A300FS, :eeet_A300FS, :mmem_A300FS, :eeem_A300FS, :mmtt_A300FS, :eett_A300FS] do
  puts "called analyzezh_A300FS task from local rakefile"
end

task :analyzezh_A300_MG_svFit => [:mmmt_A300_MG_svFit, :eemt_A300_MG_svFit, :mmet_A300_MG_svFit, :eeet_A300_MG_svFit, :mmem_A300_MG_svFit, :eeem_A300_MG_svFit, :mmtt_A300_MG_svFit, :eett_A300_MG_svFit] do
  puts "called analyzezh_A300_MG_svFit task from local rakefile"
end

task :analyzezh_ZZJetsTo4L => [:mmmt_ZZJetsTo4L, :eemt_ZZJetsTo4L, :mmet_ZZJetsTo4L, :eeet_ZZJetsTo4L, :mmem_ZZJetsTo4L, :eeem_ZZJetsTo4L, :mmtt_ZZJetsTo4L, :eett_ZZJetsTo4L] do
  puts "called analyzezh_ZZJetsTo4L task from local rakefile"
end

task :analyzezh_mg => [:mmmt_mg, :eemt_mg, :mmet_mg, :eeet_mg, :mmem_mg, :eeem_mg, :mmtt_mg, :eett_mg] do
  puts "called analyzezh_mg task from local rakefile"
end

task :analyzezh_data => [ :data_only_mmmt, :data_only_eemt, :data_only_mmet, :data_only_eeet, :data_only_mmem, :data_only_eeem, :data_only_mmtt, :data_only_eett] do
  puts "called analyzezh_data task from local rakefile"
end

task :analyzezh_ggzz => [:mmmt_ggzz, :eemt_ggzz, :mmet_ggzz, :eeet_ggzz, :mmem_ggzz, :eeem_ggzz, :mmtt_ggzz, :eett_ggzz] do
  puts "called analyzezh_zz task from local rakefile"
end

task :abdollah_sync => [:abdollah_sync_mmmt, :abdollah_sync_eemt, :abdollah_sync_mmet, :abdollah_sync_eeet,  :abdollah_sync_mmem, :abdollah_sync_eeem,  :abdollah_sync_mmtt, :abdollah_sync_eett] do
end

task :analyzezh_signal => [:mmmt_signal_only, :eemt_signal_only, :mmet_signal_only, :eeet_signal_only, :mmem_signal_only, :eeem_signal_only, :mmtt_signal_only, :eett_signal_only] do
  puts "called analyzezh_signal task from local rakefile"
end

task :mmmt_ks => get_analyzer_results("ZHAnalyzeMMMT", samples['key_shapes'])
task :eemt_ks => get_analyzer_results("ZHAnalyzeEEMT", samples['key_shapes'])
task :mmet_ks => get_analyzer_results("ZHAnalyzeMMET", samples['key_shapes'])
task :eeet_ks => get_analyzer_results("ZHAnalyzeEEET", samples['key_shapes'])
task :mmem_ks => get_analyzer_results("ZHAnalyzeMMEM", samples['key_shapes'])
task :eeem_ks => get_analyzer_results("ZHAnalyzeEEEM", samples['key_shapes'])
task :mmtt_ks => get_analyzer_results("ZHAnalyzeMMTT", samples['key_shapes'])
task :eett_ks => get_analyzer_results("ZHAnalyzeEETT", samples['key_shapes'])

task :analyzezh_ks => [:mmmt_ks, :eemt_ks, :mmet_ks, :eeet_ks, :mmem_ks, :eeem_ks, :mmtt_ks, :eett_ks] do
  puts "called analyzezh_ks task from local rakefile"
end

task :analyzezh_fullsim => [:mmmt_fs, :eemt_fs, :mmet_fs, :eeet_fs, :mmem_fs, :eeem_fs, :mmtt_fs, :eett_fs] do
  puts "called analyzezh_fullsim task from local rakefile"
end

task :analyzezh_fullsim_madgraph => [:mmmt_fs_mg, :eemt_fs_mg, :mmet_fs_mg, :eeet_fs_mg, :mmem_fs_mg, :eeem_fs_mg, :mmtt_fs_mg, :eett_fs_mg] do
  puts "called analyzezh_fullsim_madgraph task from local rakefile"
end

################################################################################
# Recipes to make data cards (plots come for free)
#  targets:
#      mmt_shapes
#      emt_shapes
#      eet_shapes
#      cards
#      copycards -> move cards to official HTT CVS area
################################################################################


# Output directories
channels = [ "mmmt", "eemt", "mmet", "eeet", "mmem", "eeem", "mmtt", "eett"]
chToRun  = ["python","ZHPlotterBase.py"]
outFiles = Array.new
channels.each do |channel|
  $plotdir = "results/#{$jobid}/plots/#{channel}/"
  directory $plotdir
  outf = "#{$plotdir}/#{channel}_shapes_#{$period}.root"
  outFiles << outf
  # puts "results/#{$jobid}/ZHAnalyze#{channel.upcase}/*" + '.root'
  # puts Dir.glob("results/#{$jobid}/ZHAnalyze#{channel.upcase}/*" + '.root').inspect
  #file outf => ['ZHPlotterBase.py'] + Dir.glob("results/#{$jobid}/ZHAnalyze#{channel.upcase}/*" + '.root') do |t|
  file outf => ['ZHPlotterBase.py'] do |t|
    chToRun << channel.upcase 
  end
end

task :plots => outFiles do |t|
  sh chToRun.join(" ")
end



$carddir = "results/#{$jobid}/cards"
 
## Combine all category shape files into the datacard project
file "#{$carddir}/shapes.root" => Dir.glob("results/#{$jobid}/plots/????/????_shapes_#{$period}.root") do |t|
  sh "mkdir -p #{$carddir}"
  sh "hadd -f #{t.name} #{t.prerequisites.join(' ')}"
  puts "#{$jobid}"
  puts "#{$period}"
  puts "results/#{$jobid}/plots/????/????_shapes_#{$period}.root"
  puts t.prerequisites
end

stat_shape_lists = [] #Dir.glob("results/#{$jobid}/plots/*/*_statshapes.txt")
# # We make these the dependency, since they are always rpoduced w/ the .txt lists
# stat_shapes = Dir.glob("results/#{$jobid}/plots/*/*_statshapes.root")

# We need to build the unc.conf and unc.vals with our stat shapes
file "#{$carddir}/unc.conf" => ["unc.conf.template", "#{$carddir}/shapes.root"] + stat_shape_lists do |t|
  # Copy the basic template
  sh "cp unc.conf.template #{t.name}"
end

file "#{$carddir}/unc.vals" => ["unc.vals.template", "#{$carddir}/shapes.root"] + stat_shape_lists do |t|
  # Copy the basic template
  #puts t.investigation
  sh "cp #{t.prerequisites[0]} #{t.name}"
end

file "#{$carddir}/cgs.conf" => "cgs.conf.template" do |t|
  sh "cp #{t.prerequisites[0]} #{t.name}"
end

def make_datacard_task(mass, channel, categories)
  card = "#{$carddir}/#{mass}/vhtt_#{channel}.txt"  
  file card => ["#{$carddir}/shapes.root", "#{$carddir}/unc.conf", "#{$carddir}/unc.vals", "#{$carddir}/cgs.conf"] do |t|
    chdir($carddir) do
      sh "mkdir -p #{channel}/#{mass}"
      # Link the shape file in the card directory so combine can run from anywhere
      chdir("#{channel}/#{mass}") do
        sh "rm -f shapes.root"
        sh "ln -s ../../shapes.root"
      end
      if categories == ''
        sh "create-datacard.py -i shapes.root -o #{channel}/#{mass}/azhtt_#{channel}_1_8TeV.txt #{mass}"
      else
        sh "create-datacard.py -i shapes.root -o #{channel}/#{mass}/azhtt_#{channel}_1_8TeV.txt #{mass} --categories '#{categories}'"
      end
    end
  end
  return card
end

task :cards => []

cardmasses = Array[220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350]

cardmasses.each do |mass|
  task :cards => make_datacard_task(mass, '4l', '')
  channels.each do |channel|
      if channel == 'mmem'
        channel = 'mmme'
      end
      task :cards => make_datacard_task(mass, channel, channel+'_zh')
  end
end

################################################################################
### Computing the limits                         ###############################
################################################################################

$limitdir=$carddir

limitFiles = Array[]
tagetsByChannel = Hash[]
(['4l'] + channels).each do |channel|
  cardmasses.each do |mass|  
    target="#{$limitdir}/#{channel}/#{mass}/higgsCombineTest-exp.Asymptotic.mH#{mass}.root"
    limitFiles << target
    if tagetsByChannel.has_key?("channel")
      tagetsByChannel[channel] << target
    else
      tagetsByChannel[channel] = [target]
    end
    file target => ["#{$carddir}/#{mass}/vhtt_#{channel}.txt"] do |t|
      sh "mkdir -p #{$limitdir}/#{channel}"
      chdir("#{$limitdir}/#{channel}") do
        #sh "limit.py --asymptotic #{mass}"
         sh "limit.py --tanb+ #{mass}" # mssm mA vs. tanb plane
         sh "lxb-xsec2tanb.py --condor #{mass}"
      end
    end
  end
end
task :limits => limitFiles

################################################################################
### making the brazil plots                         ############################
################################################################################
plotfiles = Array[]
(['4l'] + channels).each do |channel|
  target="#{$limitdir}/#{channel}/#{channel}_limit.root"
  plotfiles << target
  file target => tagetsByChannel[channel] do |t|
    chdir("#{$limitdir}") do
      sh "plot asymptotic #{ENV['CMSSW_BASE']}/src/HiggsAnalysis/HiggsToTauTau/python/layouts/sm_vhtt_layout.py #{channel}"
      sh "mv limits_limit.root #{channel}/#{channel}_limit.root"
      sh "mv #{channel}_limit.* #{channel}/."
    end
  end
end
task :limitplots => plotfiles

# ################################################################################
# ### Copying card configuration to official place ###############################
# ################################################################################
# 
# #$httcombodir="#{ENV['CMSSW_BASE']}/src/HiggsAnalysis/HiggsToTauTau/setup/vhtt"
# $httcombodir="/afs/hep.wisc.edu/cms/efriis/Limits2/src/HiggsAnalysis/HiggsToTauTau/setup/vhtt"
# 
# file "#{$httcombodir}/cgs-sm-#{$period}-00.conf" => ["#{$carddir}/cgs.conf"] do |t|
#     puts t.investigation
#   sh "cp -v #{t.prerequisites[0]} #{t.name}"
# end
# 
# file "#{$httcombodir}/unc-sm-#{$period}-00.conf" => ["#{$carddir}/unc.conf"] do |t|
#   sh "cp -v #{t.prerequisites[0]} #{t.name}"
# end
# 
# file "#{$httcombodir}/unc-sm-#{$period}-00.vals" => ["#{$carddir}/unc.vals"] do |t|
#   sh "cp -v #{t.prerequisites[0]} #{t.name}"
# end
# 
# file "#{$httcombodir}/vhtt_llt.inputs-sm-#{$period}.root" => ["#{$carddir}/shapes.root"] do |t|
#   sh "cp -v #{t.prerequisites[0]} #{t.name}"
# end
# 
# task :copycards => [
#   "#{$httcombodir}/cgs-sm-#{$period}-00.conf",
#   "#{$httcombodir}/unc-sm-#{$period}-00.conf",
#   "#{$httcombodir}/unc-sm-#{$period}-00.vals",
#   "#{$httcombodir}/vhtt_llt.inputs-sm-#{$period}.root"]  do |t|
#     puts t.investigation
#   end
